'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing study assistance to students.
 * Now uses the dual AI service with automatic fallback between Google AI and OpenAI.
 */

import { provideStudyAssistanceWithFallback } from '@/ai/services/dual-ai-service';
import { z } from 'genkit';

const ProvideStudyAssistanceInputSchema = z.object({
  question: z.string().describe('The question the student needs assistance with.'),
  context: z.string().describe('Relevant context for the question, such as the course name or topic. This could also be "General Chat".'),
});
export type ProvideStudyAssistanceInput = z.infer<typeof ProvideStudyAssistanceInputSchema>;

const ProvideStudyAssistanceOutputSchema = z.object({
  isRelevant: z.boolean().describe('Whether the question is relevant to the provided context. If the context is "General Chat", this should always be true.'),
  answer: z.string().describe('The answer to the question or a statement directing the user to the General Chat.'),
});
export type ProvideStudyAssistanceOutput = z.infer<typeof ProvideStudyAssistanceOutputSchema>;

export async function provideStudyAssistance(input: ProvideStudyAssistanceInput): Promise<ProvideStudyAssistanceOutput> {
  try {
    const result = await provideStudyAssistanceWithFallback(input);
    
    // Log which provider was used
    console.log(`AI Response generated by: ${result.provider}`);
    
    return {
      isRelevant: true,
      answer: result.answer
    };
  } catch (error) {
    console.error('All AI providers failed:', error);
    
    // Ultimate fallback
    return {
      isRelevant: true,
      answer: `I apologize, but I'm experiencing technical difficulties with my AI services. Here's a basic response to your question: "${input.question}"\n\n**General Study Tips:**\n- Break complex topics into smaller parts\n- Use examples and analogies to understand concepts\n- Practice regularly and ask specific questions\n- Connect new information to what you already know\n\nPlease try asking your question again, or contact support if the issue persists.`
    };
  }
}
