
export const universities = [
  "Arizona State University",
  "Auburn University",
  "Boston College",
  "Boston University",
  "Brandeis University",
  "Brown University",
  "California Institute of Technology (Caltech)",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Clemson University",
  "College of William & Mary",
  "Colorado State University",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Duke University",
  "ETH Zurich",
  "Emory University",
  "Florida State University",
  "George Washington University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Georgia State University",
  "Harvard University",
  "Imperial College London",
  "Indiana University Bloomington",
  "Iowa State University",
  "Johns Hopkins University",
  "Kansas State University",
  "Louisiana State University",
  "Massachusetts Institute of Technology (MIT)",
  "McGill University",
  "Michigan State University",
  "New York University (NYU)",
  "North Carolina State University",
  "Northeastern University",
  "Northwestern University",
  "Ohio State University",
  "Pennsylvania State University",
  "Princeton University",
  "Purdue University",
  "Rice University",
  "Rutgers University-New Brunswick",
  "Stanford University",
  "Stony Brook University",
  "Syracuse University",
  "Texas A&M University",
  "Tufts University",
  "University at Buffalo",
  "University of Alabama",
  "University of Arizona",
  "University of Arkansas",
  "University of British Columbia",
  "University of California, Berkeley (UCB)",
  "University of California, Davis (UCD)",
  "University of California, Irvine (UCI)",
  "University of California, Los Angeles (UCLA)",
  "University of California, San Diego (UCSD)",
  "University of California, Santa Barbara (UCSB)",
  "University of California, Santa Cruz (UCSC)",
  "University of Cambridge",
  "University of Chicago",
  "University of Colorado Boulder",
  "University of Connecticut",
  "University of Delaware",
  "University of Florida",
  "University of Georgia",
  "University of Illinois Urbana-Champaign",
  "University of Iowa",
  "University of Kansas",
  "University of Kentucky",
  "University of Maryland, College Park",
  "University of Michigan-Ann Arbor",
  "University of Minnesota",
  "University of Mississippi",
  "University of Missouri",
  "University of Nebraska-Lincoln",
  "University of New Mexico",
  "University of North Carolina at Chapel Hill",
  "University of Oklahoma",
  "University of Oregon",
  "University of Oxford",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of South Carolina",
  "University of Southern California (USC)",
  "University of Tennessee",
  "University of Texas at Austin",
  "University of Toronto",
  "University of Utah",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Vanderbilt University",
  "Virginia Tech",
  "Wake Forest University",
  "Washington State University",
  "Yale University"
];
